### ISSUE TITLE
Accuracy when data imported.

### ISSUE THREAD

**Issue by sukzy** [HilmiZul/estats#2]
I have trouble when importing data from xls file. the accuracy less than 70%.
and... deadline are close 😂

**Comment by HilmiZul** [comment]
i have done for this.
check this out: https://github.com/HilmiZul/estats/commit/6c219b562899c6a95bb426b834d0def4adb1cfcf

😁

**Comment by sukzy** [comment]
I have try to import data and it's work. but I'm no sure for another month 😭

**Comment by sukzy** [comment]
good job!

**Comment by HilmiZul** [comment]
> I have try to import data and it's work. but I'm no sure for another month 😭

because raw data. maybe manually will be oke for this problem. if use this method, why we build this app? 🤣 

anyway, thank you for feedback. I hope you enjoy using this app 😆 👍
